version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: .env
    # restart: on-failure
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: monouser
      POSTGRES_PASSWORD: monopassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: 'bitnami/redis:7.2'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  # # Use Redis Commander to view Cache content
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #     - HTTP_USER=root
  #     - HTTP_PASSWORD=root
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - app-network
  #   depends_on:
  #     - redis

volumes:
  pgdata:
  redis:
  redis-config:


networks:
  app-network:
    driver: bridge
